# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

steps:
- checkout: self
  persistCredentials: true

- task: TouchdownBuildTask@1
  inputs:
    environment: 'PRODEXT'
    teamId: '26357'
    authType: 'OAuth'
    authId: 'e2274d3e-e6e3-4d29-8988-b0b0bdf62618'
    authKey: 'j.tZn1xz1Mmvz6t_2IG~Othbi_Tq88-7h8'
    resourceFilePath: |
      */Microsoft.Teams.Apps.RemoteSupport/Resources/Strings.resx
      */Microsoft.Teams.Apps.RemoteSupport.Configuration/Resources/Strings.resx
    cultureMappingType: 'None'
    appendRelativeDir: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Show Touchdown output
      git status
      
      # Show post-processed output
      git status
      
      # Check in localized files to temp branch
      git checkout -b tdbuild/build-$env:BUILD_BUILDID
      git add --all
      git config --global user.name "Build Pipeline"
      git commit -am "Localized resource files generated by tdbuild"
      git push --set-upstream origin tdbuild/build-$env:BUILD_BUILDID